services:
    kafka1:
        image: imdhruv99/kafka:1.0.0
        container_name: kafka1
        ports:
            - "9092:9092" # Broker port
            - "9093:9093" # Controller port
            - "9999:9999" # JMX
        environment:
            KAFKA_NODE_ID: 1
            KAFKA_PROCESS_ROLES: broker,controller
            KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
            KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:9092,CONTROLLER://kafka1:9093
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
            KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
            KAFKA_CLUSTER_ID: kafka-cluster-001
        volumes:
            - kafka1-data:/var/lib/kafka/data
        networks:
            - kafka-network
    kafka2:
        image: imdhruv99/kafka:1.0.0
        container_name: kafka2
        ports:
            - "19092:9092"
            - "19093:9093"
            - "19999:9999"
        environment:
            KAFKA_NODE_ID: 2
            KAFKA_PROCESS_ROLES: broker,controller
            KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
            KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka2:9092,CONTROLLER://kafka2:9093
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
            KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
            KAFKA_CLUSTER_ID: kafka-cluster-001
        volumes:
            - kafka2-data:/var/lib/kafka/data
        networks:
            - kafka-network

    kafka3:
        image: imdhruv99/kafka:1.0.0
        container_name: kafka3
        ports:
            - "29092:9092"
            - "29093:9093"
            - "29999:9999"
        environment:
            KAFKA_NODE_ID: 3
            KAFKA_PROCESS_ROLES: broker,controller
            KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
            KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka3:9092,CONTROLLER://kafka3:9093
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
            KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
            KAFKA_CLUSTER_ID: kafka-cluster-001
        volumes:
            - kafka3-data:/var/lib/kafka/data
        networks:
            - kafka-network

    kafka-ui:
        image: provectuslabs/kafka-ui:latest
        container_name: kafka-ui
        ports:
            - "8080:8080"
        environment:
            KAFKA_CLUSTERS_0_NAME: kafka-cluster-001
            KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:9092,kafka2:9092,kafka3:9092
        networks:
            - kafka-network

volumes:
    kafka1-data:
    kafka2-data:
    kafka3-data:

networks:
  kafka-network:
    driver: bridge
